import streamlit as st

for k, v in st.session_state.items():
    st.session_state[k] = v

title_model = "LNG-to-Power Financial Model (LNG2P-FM) App."


section_introduction = r"""
This brief documentation explain a financial modelling web-based software application (LNG2P-FM App) 
for electricity production from liquefied natural gas (LNG). The App is designed to facilitate discussions 
among stakeholders involved in the LNG-to-Power value chain. It serves as a vital tool for enhancing 
communication and decision-making processes among various parties, including: project developers, financiers and
regulatory bodies. Project developers can use the App to model potential financial outcomes and assess project feasibility, 
financiers (investors) can evaluate the financial risks and returns associated with funding LNG-to-Power projects while 
regulatory bodies can analyze the impact of regulatory frameworks on project viability and sustainability.
The LNG2P-FM App is designed for ease of use, it allows stakeholders to input data and generate financial models quickly, it
provides customizable scenarios where users can create multiple financial scenarios to evaluate different 
project conditions and strategies, and facilitate real-time collaboration where stakeholders can share 
insights and feedback in real-time, enhancing the decision-making process, and provide comprehensive reporting 
where it provides detailed reports on financial metrics, helping stakeholders understand project viability at a 
glance.

To illustrate the functionality of the App, a financial model for case study of gas to electricity generation as 
per the IRP2019 and NERSA determinations is developed. In electricity generation, there are usually three 
types of operations: baseload, mid-merit, and peaking, which are related to the utilization of a power plant. 
The capacity (load) factor refers to the utilization rate of a power plant in these operations. The operations 
are also associated with conversion efficiency of feedstock (natural gas in this context) to electricity. 
In this case study, three load factors (baseload, mid-merit, and peaking) corresponding to these modes of operations
are considered. A baseload load factor indicates a high level of consistent power generation, meaning the 
plant operates near full capacity most of the time, resulting in a high load factor; a peaking load factor indicates 
a low load factor, meaning the plant operates at low capacity most of the time because it only operates during 
brief periods of high electricity demand, such as peak hours; and a mid-merit load factor bridges the gap between 
baseload and peaking periods. These load factors are the basis of the three scenarios presented in this case study
and the sidebar on the dasboard page provides three slides for ease setting of the load factors for these scenarios.
The dashboard also provides edit panel for setting specific technological parameters of power plants used in the
study.

The App presents four types of bar charts which are generated by a financial model explained below. The first chart 
has two axes; the left-hand side presents generated electricity in Petajoules and the right-hand side shows the 
amount of LNG requied to generate electricity in MTPA. The demand projections are divided into three categories, 
namely: baseload gas demand, mid-merit gas demand and peaking gas demand. The categories are due to the mode of 
operation of power plants. The LNG indicates that the LNG handling capacity, at an import terminal, required 
running at baseload, mid-merit, and peaking periods are respectively. The second bar chart shows the $$ \text{CO}_{2} $$ 
equivalent of greenhouse gas emissions and the main objective of this chart is to evaluate the emissionreduction 
because of switching from coal- and diesel-fired power station to gas-fired power station. The third chart provides
the lifetime total discounted consts associated with the scenarios and the power plants included in the study,
while the fourth chart provide an average of electricity price if the investment break even at the end of the 
operational life. Both charts are a modern and fast-spreading technique for the evaluation of investment LNG to
power proposals. The App also provides sensitivity analysis of parameters that affect the financial viability
of LNG-to-Power projects and the charts are depicted on 'LNG2P Sensitivity Analysis' page. The parameters included
in the sensitivity analysis are discount rate, load factor, efficiency rate, fuel costs, carbon costs, exchange rate,
and operational lifetime of a plant.



"""
# Baseload gas demand refers to the demand if the power plants are
# to run continuously at a consistent level to meet the minimum electricity demand around the
# clock, where Mid-merit gas demand refers to the demand if the plants are to operate to fill the
# gap between consistent baseload power and peak. The peaking demand refers to the demand
# that is required if the power plants are to operate only during high demand periods. Figure 11
# shows that the two power stations would require 72 PJ of natural gas to run at baseload, 57 PJ to
# run at Mid-merit and 14 PJ to run only at peaking periods. . Figure 16 shows the corresponding GHG
# emissions and carbon tax savings because of switching to natural gas.

# Financial modeling is one of the most important tools in the energy sector, enabling various
# stakeholders -- such as project developers, investors, and financiers -- to evaluate a project's
# financial viability, understand associated risks, and forecast future returns. The model has recently
# gained significant popurlarity amid the global shift towards decarbonization and evolving landscape
# of energy sector. Formulating robust financial models requires not only technical expertise but also a deep understanding
# of the various elements that influence energy investments. These models help stakeholders make informed
# decisions by providing insights into: (1) cost structures for clearly understanding capital investment,
# fixed and variable operation and maintenance, fuel, carbon tax, and decommitioning costs associated with
# electricity production. (2) revenue projections by estimating future cash flows based on electricity demand
# and pricing, and (3) risk assessment for evaluating potential risks such as regulatory changes,
# market volatility, and technological advancements.


# The LNG2P-FM App acts as
# 1. To evaluate the financial viability of an LNG-to-Power project, it is essential to analyze several
# key financial indicators, including projected financial cash flows, the internal rate of return (IRR),
# and the net present value (NPV). These indicators assist stakeholders understand if the project
# aligns with their financial objectives or not.


# This page presents an overview documentation of a web-based software
# application (LNG2P-FM App) to facilitate the intrinsicilly difficult discussion among the
# statekeholders along the LNG-to-Power value chain. The App acts as a mediator between stakeholders
# for decision-making process, particularly serves:


# To evaluate financial viability of LNG-to-Power project. This can be achieved by projecting financial cash flow,
# internal rate of return (IRR), net present value (NPV). These indicators enable the stakeholders
# to determine whether a project is aligns with their financial goals."""

section_model = """### The Financial Model """
model_description = """The financial model implemented here is based on levelised cost of electricity (LCOE).
    The calculation of LCOE can be viewed in two ways; it can be defined as an equivalent of the present value of 
    the sum of discounted revenues (unit price of electricity multiplies by generated electricity) and present 
    value of sum of discounted costs or as a metric used to estimate the average cost (capital, fixed and\or 
    variable operations and maintenance, fuel, carbon, and decommissioning) of generating electricity over the 
    lifetime of a generic power plant. That is, Equation 1 show the benefits on the left-hand side of the discounted
    sum of benefits while on the right-hand side show the discounted sum of costs. 
    """
#  It is calculated by dividing the discounted total lifetime costs -- such as ) by the total lifetime
#     electrical production.


cba_model = r"""
    \begin{align}
    \underbrace{ {\sum_{s,t,y} \frac{\text{P}_{MWh} * \text{E}_{s,t,y}}{(1 + r_{t})^y}} }_{\text{Discounted Benefits}} = 
    \underbrace{{\sum_{s,t,y} \frac{(\text{CAPEX}_{s,t,y} + \text{FO\&M}_{s,t,y} + \text{VO\&M}_{s,t,y} + \text{Fuel}_{s,t,y} + 
    \text{Carbon}_{s,t,y} + \text{D}_{s,t,y})} {(1 + r_{t})^y}}}_{\text{Discounted Costs}}
    \end{align}"""

# \forall s \in S, t \in T, y \in Y
# model = r"""
#     $$
#     \underbrace{ {\sum_{t}^{T} \frac{\text{P}_{MWh} * \text{E}_{t}}{(1 + r)^t}} }_{\text{Discounted Benefits}} = \underbrace{{\sum_{t}^{T} \frac{(\text{CAPEX}_{t} + \text{FO\&M}_{t} + \text{VO\&M}_{t} + \text{Fuel}_{t} + \text{Carbon}_{t} + \text{D}_{t})} {(1 + r)^t} } }_{\text{Discounted Costs}}
#     $$"""


PMWh = r""" 
    Since $$\text{P}_{MWh}$$ is constant over time, it can be brought out of summation and the equation can be 
    transformed into Equation 2, the constant $$\text{P}_{MWh}$$ defined as levelised cost of electricity (LCOE).
    That is, LCOE essentially represents the average minimum price at which electricity must be sold to cover 
    the plant's costs over its lifetime. """

lcoe_model = r"""
    \begin{align}
    \text{LCOE} = \text{P}_{MWh} = \frac{{\sum_{s,t,y} \frac{(\text{CAPEX}_{s,t,y} + \text{FO\&M}_{s,t,y} + \text{VO\&M}_{s,t,y} + 
    \text{Fuel}_{s,t,y} + \text{Carbon}_{s,t,y} + \text{D}_{s,t,y})} {(1 + r)^y}}}{\sum_{s,t,y} \frac{\text{E}_{s,t,y}} {(1 + r)^{y}}}
    \end{align}
    """

set_model = r"""
Where:
- $ s \in S = $ the set of load factor scenarios,
- $ t \in T = $ the set of power stations, and
- $ y \in Y = $ the power plant lifetime years.
"""


# : The LCOE is the net present value ($$\text{NPV}$$) of the total life cycle costs of the project divided by a discounted quantity of energy generated over the system life.
# lcoe = r"""
#     $$
#     \text{LCOE} = \text{P}_{MWh} = \frac{\sum_{t}^{T}(\text{CAPEX}_{t} + \text{FO\&M}_{t} + \text{VO\&M}_{t} + \text{Fuel}_{t} + \text{Carbon}_{t} + \text{D}_{t}) * (1 + r)^{-t}}
#     {\sum_{t}^{T} \text{E}_{t} * (1 + r)^{-t}}
#     $$"""

# guide = """This guide offers a detailed exploration of financial modeling for energy projects, unpacking its
#     structure, key components, and the strategies required to build comprehensive and reliable models that
#     can withstand the scrutiny of investors and stakeholders."""
# are the core components that form the backbone of such models:


parameters = r"""Key components (decision variables) of the financial model which capture unique dynamics of an energy project 
while maintaining clarity and precisionare explained below:
1. Capital costs ($$ \text{CAPEX}_{s,t,y} $$) forms the foundation of any energy project’s financial structure. 
These costs include not only land acquisition and equipment, but also other costs such as construction labor, grid 
interconnection, and regulatory compliance. It is a function of two parameters -- installed capacity and unit cost 
per installed capacity. The evelopers rely on detailed proposals from Engineering, Procurement, and Construction 
(EPC) contractors to estimate these parameters..

2. Fixed operating and maintenance costs ($$\text{FO\&M}_{s,t,y} $$) represent recurring annual costs associated
with operating of a plant during its lifetime regardless of the amount of electricity produced. These expenses 
may include routine maintenance and repairs to administrative and insurance costs. In this model, they are calculated
as a percentage of total overnight costs of a project.

3. Variable operating and maintenance  costs ($$ \text{VO\&M}_{s,t,y} $$) are those that are associated with the 
plant's electricity production and may include oil and lubricant costs, and unplanned repair/maintenance costs.
in this model, these costs are calculated by multiplying electricity produced by a cost per unit of electricity 
produced.

4. Fuel costs ($$ \text{Fuel}_{s,t,y} $$) refers to the costs associated with an imported LNG expenditure. In this
model, the LNG costs are calculated by deviding the amount of electricity generated with the plant's efficiency rate
and then converting the results to tonnes of LNG. The tonnes are then multiplies by cost per unit of LNG tonnes.

5. Carbon Tax costs ($$ \text{Carbon}_{s,t,y}$$) are externality costs associated with emitting greenhouse gas
emissions into the atmosphere and are one key requlatory instruments used by different jurisdictions to curb 
emissions. In this model, the costs are calculated by multiplying tonnes of LNG used to generate electricity 
with the corresponding emission factor to convert them into emission equivalant and then multiplying the 
results by cost per unit of $CO_{2}$ equivalent decided by a requlatory bodies. 

6. Decommissioning Costs: All energy projects eventually require decommissioning, whether dismantling 
wind turbines or managing solar panel recycling. Financial models must include a reserve fund for these 
expenses to ensure environmental compliance and financial stability in the project’s final stages.

7. Electricity production ($$ \text{E}_{s,t,y} $$) is a function of installed capacity of a plant and 
capacity factor. The calculation of the corresponding volumes of LNG is done through a  conversion 
factor. 

Revenue Projections: Revenue modeling is a cornerstone of the financial model, often based on projected energy production and pricing mechanisms. For projects with PPAs, revenues are more predictable, anchored in fixed long-term agreements. However, market-based projects—where electricity prices fluctuate—require more sophisticated modeling to simulate variable revenue streams. Energy generation forecasts should factor in:
 Seasonal and weather-driven variability.
 Equipment degradation rates.
 Grid curtailments or downtime.
"""

# 4. Financing Structure: The financing of energy projects is typically a blend of debt and equity. The model must detail repayment schedules, interest rates, and equity returns. For projects financed via non-recourse project finance structures, lenders will scrutinize metrics like DSCR and Loan Life Coverage Ratio (LLCR). These metrics demonstrate the project’s ability to meet debt obligations and deliver returns to investors.
# 5. Discounted Cash Flow (DCF) Analysis: DCF analysis is at the heart of evaluating an energy project’s financial viability. By discounting future cash flows to their present value, stakeholders can assess profitability relative to the weighted average cost of capital (WACC). A detailed DCF model incorporates:
# Annual cash inflows from energy sales.
# Tax impacts and depreciation schedules.
# Residual value at the project’s end-of-life.
# Sensitivity analyses, evaluating scenarios like lower energy prices or higher operating costs, further enhance the robustness of the DCF.
# 6. Taxation and Incentives: Tax structures, including corporate income taxes and value-added taxes (VAT), directly influence project economics. In many jurisdictions, energy projects benefit from incentives like accelerated depreciation, investment tax credits (ITC), or production tax credits (PTC). Accurately incorporating these incentives can substantially improve projected returns.


### Why Financial Modeling is Essential in Energy Projects

rationale = """Energy projects are inherently complex, requiring significant capital investments 
    before yielding returns. Whether you are constructing a large-scale solar farm, a wind energy 
    park, or a natural gas plant, the financial stakes are immense. Upfront expenditures for land 
    acquisition, engineering, procurement, and construction often run into millions or billions of 
    dollars. These costs are offset over decades through revenue generated by selling electricity, 
    leveraging power purchase agreements (PPAs), or participating in spot markets."""

# demand, emissions = st.columns(2)
# with demand:
#     st.image(
#         "financial_model_app/asserts/demand.png", caption="Sunrise by the mountains"
#     )
# with emissions:
#     pass

# The financial model acts as a decision-making framework, serving to:
# 1. Evaluate Financial Feasibility: By projecting cash flows, internal rate of return (IRR), and
# net present value (NPV), stakeholders can determine whether a project aligns with financial
# objectives.
# 2. Inform Investment Decisions: Financial models provide lenders and equity investors with
# clarity on the risks and potential returns.
# 3. Guide Negotiations: Metrics such as debt service coverage ratio (DSCR) support negotiations
# with banks and financiers.
# 4. Monitor Ongoing Performance: Post-construction, models offer a baseline for assessing actual
# performance against projections and identifying optimization opportunities.

title_case_study = "### Case Study"


abstract = """South Africa faces a difficult transition from a high to a low carbon economy while ensuring 
    energy security and affordability. To achieve this, the country has chosen natural gas as one of its fuel 
    sources for lowering greenhouse gas emissions. Therefore, this study considers low, medium, and high gas 
    demand scenarios. The findings indicate that the move will result in a large increase in gas demand in 
    the short to medium term, while at the same time reducing greenhouse gas emissions."""

energy_projects = """ 
    Energy projects are inherently complex, requiring significant capital investments before yielding
    returns. Whether you are constructing a large-scale solar farm, a wind energy park, or a natural gas
    plant, the financial stakes are immense. Upfront expenditures for land acquisition, engineering,
    procurement, and construction often run into millions or billions of dollars. These costs are offset
    over decades through revenue generated by selling electricity, leveraging power purchase agreements
    (PPAs), or participating in spot markets."""

policy = """
    ### Policy 
    Policy and regulatory impacts...
"""

st.title(title_model)
st.write(section_introduction)
st.write(section_model)
st.write(model_description)
st.latex(cba_model)
st.write(PMWh)
st.latex(lcoe_model)
st.write(set_model)
st.write(parameters)
# st.write(title_case_study)
# st.write(abstract)
# st.write(energy_projects)
# st.write(policy)
model_header = """The Financial Model """
model_body = """The financial model implemented here is based on levelised cost of electricity (LCOE).
    The calculation of LCOE can be viewed in two ways; it can be defined as an equivalent of the present value of 
    the sum of discounted revenues (unit price of electricity multiplies by generated electricity) and present 
    value of sum of discounted costs or as a metric used to estimate the average cost (capital, fixed and\or 
    variable operations and maintenance, fuel, carbon, and decommissioning) of generating electricity over the 
    lifetime of a generic power plant. That is, Equation 1 show the benefits on the left-hand side of the discounted
    sum of benefits while on the right-hand side show the discounted sum of costs. 
    """
PMWh = r""" 
    Since $$\text{P}_{MWh}$$ is constant over time, it can be brought out of summation and the equation can be 
    transformed into Equation 2, the constant $$\text{P}_{MWh}$$ defined as levelised cost of electricity (LCOE).
    That is, LCOE essentially represents the average minimum price at which electricity must be sold to cover 
    the plant's costs over its lifetime. """


section_introduction = r"""
This brief documentation explain a financial modelling web-based software application (LNG2P-FM App) 
for electricity production from liquefied natural gas (LNG). The App is designed to facilitate discussions 
among stakeholders involved in the LNG-to-Power value chain. It serves as a vital tool for enhancing 
communication and decision-making processes among various parties, including: project developers, financiers and
regulatory bodies. Project developers can use the App to model potential financial outcomes and assess project feasibility, 
financiers (investors) can evaluate the financial risks and returns associated with funding LNG-to-Power projects while 
regulatory bodies can analyze the impact of regulatory frameworks on project viability and sustainability.
The LNG2P-FM App is designed for ease of use, it allows stakeholders to input data and generate financial models quickly, it
provides customizable scenarios where users can create multiple financial scenarios to evaluate different 
project conditions and strategies, and facilitate real-time collaboration where stakeholders can share 
insights and feedback in real-time, enhancing the decision-making process, and provide comprehensive reporting 
where it provides detailed reports on financial metrics, helping stakeholders understand project viability at a 
glance.

To illustrate the functionality of the App, a financial model for case study of gas to electricity generation as 
per the IRP2019 and NERSA determinations is developed. In electricity generation, there are usually three 
types of operations: baseload, mid-merit, and peaking, which are related to the utilization of a power plant. 
The capacity (load) factor refers to the utilization rate of a power plant in these operations. The operations 
are also associated with conversion efficiency of feedstock (natural gas in this context) to electricity. 
In this case study, three load factors (baseload, mid-merit, and peaking) corresponding to these modes of operations
are considered. A baseload load factor indicates a high level of consistent power generation, meaning the 
plant operates near full capacity most of the time, resulting in a high load factor; a peaking load factor indicates 
a low load factor, meaning the plant operates at low capacity most of the time because it only operates during 
brief periods of high electricity demand, such as peak hours; and a mid-merit load factor bridges the gap between 
baseload and peaking periods. These load factors are the basis of the three scenarios presented in this case study
and the sidebar on the dasboard page provides three slides for ease setting of the load factors for these scenarios.
The dashboard also provides edit panel for setting specific technological parameters of power plants used in the
study.

The App presents four types of bar charts which are generated by a financial model explained below. The first chart 
has two axes; the left-hand side presents generated electricity in Petajoules and the right-hand side shows the 
amount of LNG requied to generate electricity in MTPA. The demand projections are divided into three categories, 
namely: baseload gas demand, mid-merit gas demand and peaking gas demand. The categories are due to the mode of 
operation of power plants. The LNG indicates that the LNG handling capacity, at an import terminal, required 
running at baseload, mid-merit, and peaking periods are respectively. The second bar chart shows the $$ \text{CO}_{2} $$ 
equivalent of greenhouse gas emissions and the main objective of this chart is to evaluate the emissionreduction 
because of switching from coal- and diesel-fired power station to gas-fired power station. The third chart provides
the lifetime total discounted consts associated with the scenarios and the power plants included in the study,
while the fourth chart provide an average of electricity price if the investment break even at the end of the 
operational life. Both charts are a modern and fast-spreading technique for the evaluation of investment LNG to
power proposals. The App also provides sensitivity analysis of parameters that affect the financial viability
of LNG-to-Power projects and the charts are depicted on 'LNG2P Sensitivity Analysis' page. The parameters included
in the sensitivity analysis are discount rate, load factor, efficiency rate, fuel costs, carbon costs, exchange rate,
and operational lifetime of a plant.



"""
# Baseload gas demand refers to the demand if the power plants are
# to run continuously at a consistent level to meet the minimum electricity demand around the
# clock, where Mid-merit gas demand refers to the demand if the plants are to operate to fill the
# gap between consistent baseload power and peak. The peaking demand refers to the demand
# that is required if the power plants are to operate only during high demand periods. Figure 11
# shows that the two power stations would require 72 PJ of natural gas to run at baseload, 57 PJ to
# run at Mid-merit and 14 PJ to run only at peaking periods. . Figure 16 shows the corresponding GHG
# emissions and carbon tax savings because of switching to natural gas.

# Financial modeling is one of the most important tools in the energy sector, enabling various
# stakeholders -- such as project developers, investors, and financiers -- to evaluate a project's
# financial viability, understand associated risks, and forecast future returns. The model has recently
# gained significant popurlarity amid the global shift towards decarbonization and evolving landscape
# of energy sector. Formulating robust financial models requires not only technical expertise but also a deep understanding
# of the various elements that influence energy investments. These models help stakeholders make informed
# decisions by providing insights into: (1) cost structures for clearly understanding capital investment,
# fixed and variable operation and maintenance, fuel, carbon tax, and decommitioning costs associated with
# electricity production. (2) revenue projections by estimating future cash flows based on electricity demand
# and pricing, and (3) risk assessment for evaluating potential risks such as regulatory changes,
# market volatility, and technological advancements.


# The LNG2P-FM App acts as
# 1. To evaluate the financial viability of an LNG-to-Power project, it is essential to analyze several
# key financial indicators, including projected financial cash flows, the internal rate of return (IRR),
# and the net present value (NPV). These indicators assist stakeholders understand if the project
# aligns with their financial objectives or not.


# This page presents an overview documentation of a web-based software
# application (LNG2P-FM App) to facilitate the intrinsicilly difficult discussion among the
# statekeholders along the LNG-to-Power value chain. The App acts as a mediator between stakeholders
# for decision-making process, particularly serves:


# To evaluate financial viability of LNG-to-Power project. This can be achieved by projecting financial cash flow,
# internal rate of return (IRR), net present value (NPV). These indicators enable the stakeholders
# to determine whether a project is aligns with their financial goals."""
# 4. Financing Structure: The financing of energy projects is typically a blend of debt and equity. The model must detail repayment schedules, interest rates, and equity returns. For projects financed via non-recourse project finance structures, lenders will scrutinize metrics like DSCR and Loan Life Coverage Ratio (LLCR). These metrics demonstrate the project’s ability to meet debt obligations and deliver returns to investors.
# 5. Discounted Cash Flow (DCF) Analysis: DCF analysis is at the heart of evaluating an energy project’s financial viability. By discounting future cash flows to their present value, stakeholders can assess profitability relative to the weighted average cost of capital (WACC). A detailed DCF model incorporates:
# Annual cash inflows from energy sales.
# Tax impacts and depreciation schedules.
# Residual value at the project’s end-of-life.
# Sensitivity analyses, evaluating scenarios like lower energy prices or higher operating costs, further enhance the robustness of the DCF.
# 6. Taxation and Incentives: Tax structures, including corporate income taxes and value-added taxes (VAT), directly influence project economics. In many jurisdictions, energy projects benefit from incentives like accelerated depreciation, investment tax credits (ITC), or production tax credits (PTC). Accurately incorporating these incentives can substantially improve projected returns.


### Why Financial Modeling is Essential in Energy Projects

rationale = """Energy projects are inherently complex, requiring significant capital investments 
    before yielding returns. Whether you are constructing a large-scale solar farm, a wind energy 
    park, or a natural gas plant, the financial stakes are immense. Upfront expenditures for land 
    acquisition, engineering, procurement, and construction often run into millions or billions of 
    dollars. These costs are offset over decades through revenue generated by selling electricity, 
    leveraging power purchase agreements (PPAs), or participating in spot markets."""

# demand, emissions = st.columns(2)
# with demand:
#     st.image(
#         "financial_model_app/asserts/demand.png", caption="Sunrise by the mountains"
#     )
# with emissions:
#     pass

# The financial model acts as a decision-making framework, serving to:
# 1. Evaluate Financial Feasibility: By projecting cash flows, internal rate of return (IRR), and
# net present value (NPV), stakeholders can determine whether a project aligns with financial
# objectives.
# 2. Inform Investment Decisions: Financial models provide lenders and equity investors with
# clarity on the risks and potential returns.
# 3. Guide Negotiations: Metrics such as debt service coverage ratio (DSCR) support negotiations
# with banks and financiers.
# 4. Monitor Ongoing Performance: Post-construction, models offer a baseline for assessing actual
# performance against projections and identifying optimization opportunities.

title_case_study = "### Case Study"


abstract = """South Africa faces a difficult transition from a high to a low carbon economy while ensuring 
    energy security and affordability. To achieve this, the country has chosen natural gas as one of its fuel 
    sources for lowering greenhouse gas emissions. Therefore, this study considers low, medium, and high gas 
    demand scenarios. The findings indicate that the move will result in a large increase in gas demand in 
    the short to medium term, while at the same time reducing greenhouse gas emissions."""

energy_projects = """ 
    Energy projects are inherently complex, requiring significant capital investments before yielding
    returns. Whether you are constructing a large-scale solar farm, a wind energy park, or a natural gas
    plant, the financial stakes are immense. Upfront expenditures for land acquisition, engineering,
    procurement, and construction often run into millions or billions of dollars. These costs are offset
    over decades through revenue generated by selling electricity, leveraging power purchase agreements
    (PPAs), or participating in spot markets."""

policy = """
    ### Policy 
    Policy and regulatory impacts...
"""

parameters_body_old = r"""Key components (decision variables) of the financial model which capture unique dynamics 
of an energy project while maintaining clarity and precisionare explained below:
1. Capital costs ($$ \text{CAPEX}_{s,t,y} $$) forms the foundation of any energy project’s financial structure. 
These costs include not only land acquisition and equipment, but also other costs such as construction labor, grid 
interconnection, and regulatory compliance. It is a function of two parameters -- installed capacity and unit cost 
per installed capacity. The evelopers rely on detailed proposals from Engineering, Procurement, and Construction 
(EPC) contractors to estimate these parameters..

2. Fixed operating and maintenance costs ($$\text{FO\&M}_{s,t,y} $$) represent recurring annual costs associated
with operating of a plant during its lifetime regardless of the amount of electricity produced. These expenses 
may include routine maintenance and repairs to administrative and insurance costs. In this model, they are calculated
as a percentage of total overnight costs of a project.

3. Variable operating and maintenance  costs ($$ \text{VO\&M}_{s,t,y} $$) are those that are associated with the 
plant's electricity production and may include oil and lubricant costs, and unplanned repair/maintenance costs.
in this model, these costs are calculated by multiplying electricity produced by a cost per unit of electricity 
produced.

4. Fuel costs ($$ \text{Fuel}_{s,t,y} $$) refers to the costs associated with an imported LNG expenditure. In this
model, the LNG costs are calculated by deviding the amount of electricity generated with the plant's efficiency rate
and then converting the results to tonnes of LNG. The tonnes are then multiplies by cost per unit of LNG tonnes.

5. Carbon Tax costs ($$ \text{Carbon}_{s,t,y}$$) are externality costs associated with emitting greenhouse gas
emissions into the atmosphere and are one key requlatory instruments used by different jurisdictions to curb 
emissions. In this model, the costs are calculated by multiplying tonnes of LNG used to generate electricity 
with the corresponding emission factor to convert them into emission equivalant and then multiplying the 
results by cost per unit of $CO_{2}$ equivalent decided by a requlatory bodies. 

6. Decommissioning Costs: All energy projects eventually require decommissioning, whether dismantling 
wind turbines or managing solar panel recycling. Financial models must include a reserve fund for these 
expenses to ensure environmental compliance and financial stability in the project’s final stages.

7. Electricity production ($$ \text{E}_{s,t,y} $$) is a function of installed capacity of a plant and 
capacity factor. The calculation of the corresponding volumes of LNG is done through a  conversion 
factor. 

Revenue Projection is a cornerstone of the financial model, often based on projected energy production and 
pricing mechanisms. For projects with Power Purchase Agreements(PPAs), revenues are more predictable, 
anchored in fixed long-term agreements. However, market-based projects where electricity prices fluctuate 
require more sophisticated modeling to simulate variable revenue streams. It is also crucial to understand 
that the accuracy of the model depends on externalities and\\ or incentives that are related to regulatory 
and fiscal policies in different jurisdictions. and plant's operational conditions, which must
be carefully analysed to reach an acurate decisions.
"""
